### ISSUE TITLE
Instantiation system requires a validation function

### ISSUE THREAD

**Issue by MrManiak** [BeardedManStudios/ForgeNetworkingRemastered#101]
### Version Number and Operating System(s):
23.0, Unity 2017.1.1f1, Windows 10 Pro

### Expected behavior:
Calling an instantiation method on the NetworkManager from client-side should trigger a function on the server to validate the instantiation.

### Actual behavior:
There is no way to validate instantiation requests from clients. Any client can create any instantiation prefab at any point.

### Steps to reproduce:
Call a NetworkManager instantiation method from the client and try to prevent it from server-side.

### More on this issue:
When I asked the question on discord, nobody could give me a good answer so I was told to log it on GitHub. There is nothing about this in the docs that I could find. ServerAllowRpc and ServerAllowBinaryData aren't called on instantiation and the NetworkManager.Instance.Networker.objectCreateRequested event doesn't seem to get called at all. 

What we would need is a method on the NetworkObject that works the same way as ServerAllowRpc to validate instantiation requests. The method could also be on the NetworkManager with the identifier of the NetworkObject that is about to be created.

#### [Optional] Discord Username:
MickeyMeme

**Comment by Tech305** [comment]
let me tak a look at the code and see what is happening and get back to you

On Wed, Oct 4, 2017 at 11:15 AM, Ariel Gadbois-Roy <notifications@github.com

**Comment by MrManiak** [comment]
As a kind soul in Discord pointed out, that's the job of the NetworkObjectFactory.

https://github.com/BeardedManStudios/ForgeNetworkingRemastered/blob/master/Forge%20Networking%20Remastered%20Unity/Assets/Bearded%20Man%20Studios%20Inc/Scripts/NetworkObjectFactory.cs
