### ISSUE TITLE
Before connecting to a server, see a list of available Local LAN game servers by custom name

### ISSUE THREAD

**Issue by victorMaje** [BeardedManStudios/ForgeNetworkingRemastered#104]
### Version Number and Operating System(s):
Macos 10.12.6, Forge v24.1, Unity v5.6.1f1

### Expected behavior:
Before connecting to a server, see a list of available Local LAN game servers by custom name:
John's game
Maria's game
XYZ's game

### Actual behavior:
List of Local LAN game servers can only have a name made of a device IP/port or hardcoded value:
Game 1
Game 2
Game 3

### Steps to reproduce:
Using "RefreshLocalUdpListings" & "NetWorker.localServerLocated += LocalServerLocated;", one can retrieve all the local servers & store them in a list which would show to a client the available LAN games.
The types stored in the list are structs of type BroadcastEndpoints. They contain a string Address, ushort Port & bool IsServer.
If the BroadcastEndPoints were to have an additional string field (i.e: custom), then Hosts can set that field as a custom name that is broadcasted along with the Address, Port & IsServer values. 
Clients can then use that custom name to show the game session's name instead of something else. 
This could mostly be helpful for <b>mobile devices</b>:
Instead of having a list of local LAN games like game1,game2,game3...If we use the name of the device we can have a list of available local LAN games like John's game, Maria's game, XYZ's game...

#### [Optional] Discord Username:
vikMage5#1653

**Comment by theWill** [comment]
I am interested in implementing this feature. I remember trying before and sending a string as part of the struct sent during RefreshLocalUdpListings was not sufficient to solve this. Anyone have some guidance here?

**Comment by phalasz** [comment]
I'll just put this here too so people coming here will know that we have already discussed this on discord pointing out the PR that is linked above your comment.

**Comment by phalasz** [comment]
Fix in PR #266 has been merged.
