### ISSUE TITLE
Steam integration?

### ISSUE THREAD

**Issue by Zyles** [BeardedManStudios/ForgeNetworkingRemastered#106]
Will this library support Steam?

Thanks.

**Comment by XaloX** [comment]
@Zyles It does support Steam, you need just to integrate it in.

**Comment by TylerOlsen** [comment]
I highly recommend https://github.com/Facepunch/Facepunch.Steamworks

Used in Rust (a game also developed with Unity)

**Comment by XaloX** [comment]
@TylerOlsen Indeed!! @Zyles I never tested it, but with Facepunch or any steam wrapper, I heard Steam has little to no trouble integrating code into your game.

**Comment by mcguinnessdr** [comment]
Steamworks integration was added in PR #143
