### ISSUE TITLE
Prefab with 2 networkobjects (one in root and one as child) sometimes tries to initialize the wrong behavior

### ISSUE THREAD

**Issue by dariorbun** [BeardedManStudios/ForgeNetworkingRemastered#110]
### Version Number and Operating System(s):
Version 24.1 Win10

### Expected behavior:
When you spawn a prefab that has a networkobject in the root transform and another networkobject in one of its child, both should instantiate correctly when you call the  NetworkManager.Instance.Instantiate () of the root object

### Actual behavior:
Sometimes it happens that on a client, the instantiation bugs out.
The parent networkobject gets instantiated correctly but when the child networkbehavior Initialize(NetworkObject obj) method gets called, it throws a "cannot cast to" error because the networkobject that gets passed to it is the one from the root object and not the correct one.
For example, root has class A and child class B. When the Initialize(NetworkObject obj) gets called for class B, the obj passed is classA and not classB

### Steps to reproduce:
I don't really know how to reproduce it....the same exact code sometimes works, sometimes throws the exception....sometimes works on client1, then on client2 throws the error. 
On the server it always works, though.

#### [Optional] Discord Username:
daragorn

**Comment by mcguinnessdr** [comment]
#173 Contains a more thorough explanation.
