### ISSUE TITLE
Unity 2017.2 editor doesn't connect

### ISSUE THREAD

**Issue by Nesvi** [BeardedManStudios/ForgeNetworkingRemastered#111]
### Version Number and Operating System(s):
24.2 Windows 10

### Expected behavior:
Connect from one editor server/client to other editor/build server/client in different PCs.

### Actual behavior:
It does not connect.

### Steps to reproduce:
Open Unity editor and try to connect to another PC running a build or other editor. 

#### [Optional] Discord Username:
Nesvi

**Comment by Nesvi** [comment]
DEEP_LOGGING Doesn't outputs nothing because it doesn't even connects.

**Comment by KirkStallings** [comment]
Try it with two editors on the same PC. If that works, then connecting between two PCs is likely a networking / firewall issue. To test with two editors on one PC, simply copy the entire project folder, open two instances of Unity, and open one project in one instance of Unity and the copied project in the second instance of Unity.

**Comment by mcguinnessdr** [comment]
Closing this issue, as it was likely an error with the set up, not with Forge.
