### ISSUE TITLE
Clients instantly disconnected with SocketException when using TCP.

### ISSUE THREAD

**Issue by Relic** [BeardedManStudios/ForgeNetworkingRemastered#113]
### Version Number and Operating System(s):
Windows 10 64-bit
Unity 2017.2.0f3
Forge master branch commit 9fe861e

### Expected behavior:
Ticking Use TCP property in the Multiplayer Menu script inn MultiplayerMenu.unity scene and then building & running the CubeForge example should result in CubeForge working as expected.

### Actual behavior:
Any clients connecting are instantly disconnected with a SocketException (An existing connection was forcibly closed by the remote host.)

### Steps to reproduce:
1) Import Forge to a fresh Unity project.
2) In MultiplayerMenu.unity find the Multiplayer Menu script under Canvas and tick Use TCP.
3) Build the project with MultiplayerMenu.unity as scene 0 and CubeForgeGame.unity as scene 1.
4) Start the server.
5) Try to connect using a client - the SocketException occurs here.

#### [Optional] Discord Username:
Relic#4678

#### Screenshot & Unity log:
![error](https://user-images.githubusercontent.com/2211270/33808697-22403826-ddeb-11e7-8661-4e28ee166331.PNG)
[output_log.txt](https://github.com/BeardedManStudios/ForgeNetworkingRemastered/files/1545990/output_log.txt)

**Comment by Fabpk90** [comment]
Hi!
Did someone found a fix for this?

**Comment by mcguinnessdr** [comment]
Presumably fixed in PR #189
