### ISSUE TITLE
NetworkBehavior GameObject not being spawned in the correct position

### ISSUE THREAD

**Issue by sudall** [BeardedManStudios/ForgeNetworkingRemastered#121]
### Version Number and Operating System(s):
Latest Forge, Windows 10

### Expected behavior:
A NetworkBehavior's GameObject should spawn at the position and rotation given when instantiating via the NetworkManager.

### Actual behavior:
GameObject spawns at origin with no rotation (the defaults), then is moved and rotated after creation.

### Steps to reproduce:
You should see the object for a split second show up at the origin. You can also see this in the debugger.

**Comment by NFMynster** [comment]
There's a fix for this on the official Discord.
TLDR you can call SnapInterpolation as that's what's causing the issue, since it's trying to lerp from a previous/invalid vector3, ie world origin.
