### ISSUE TITLE
Extending the <ObjectName>NetworkObject partial class to any degree breaks NCW

### ISSUE THREAD

**Issue by Nimuecrypto** [BeardedManStudios/ForgeNetworkingRemastered#132]
### Version Number and Operating System(s):
FNR24

### Expected behavior:
Since the class is marked partial, I expect to be able to extend it without breaking Network Contract Wizard.

### Actual behavior:
Extending the <ObjectName>NetworkObject class for an object to any real degree (adding public or private fields to top of class) results in NCW failing to load all network objects and appear empty even though the code works just fine at runtime.

### Steps to reproduce:
Create a network object, then create a partial class extending the <ObjectName>NetworkObject partial class.  Add a member to the class definition such as 'private int _myTestInt = 0;' and save.   Wait for compile, then open NCW and witness that it is empty.

#### [Optional] Discord Username:
CCStdIO

**Comment by wormszer** [comment]
This is happening because the NCW looks at the actual code to get its field values. And then compares this against the class attribute GeneratedInterpol and the interp json. It then indexs into this array to see if it should be interpolated. Adding a new variable will cause and out of bounds exception.

**Comment by WhelanB** [comment]
Following #216 this should no longer happen for NetworkObjects using the new attribute, however it will throw an out of bounds exception if there is a partial class present and the generated network object code has not yet been updated. A solution to this could just be to pad the interpolation array with zeroes or provide some other recovery method for the out of bounds exception.

It could be possible to allow users extending the network object via partial classes to define NCW fields in the partial class, and have the NCW pick up on these and make the necessary changes to the generated code to support syncing these fields, however I'm not sure that it is specifically the purpose of having partial classes, which is to allow users to extend them with their own code.

**Comment by phalasz** [comment]
Could this issue be closed now? It's been open for more than a year and @WhelanB added a fix that should have resolved this.
