### ISSUE TITLE
Description in readme.md

### ISSUE THREAD

**Issue by LeLocTai** [BeardedManStudios/ForgeNetworkingRemastered#14]
It would be great if someone can add some description to the readme.md file so people can know what this do without googling

**Comment by baflink** [comment]
I completely agree with you on that. I will need to come up with a very detailed readme for this. I'm also willing to take some suggestions on what should be listed in the readme :)

**Comment by LeLocTai** [comment]
Other than a brief description, I think it only need a minimal runnable example. Everything else can be in the docs, just put a link to it.

I don't think I can help much since I know next to nothing about Forge, that why I'm making this issue :)

**Comment by baflink** [comment]
Haha, good point. I'll see if there is already an example in the docs that I can copy over to the readme so that people can quickly see how it works :)

**Comment by baflink** [comment]
I've updated the description :). Let me know if there needs to be more information or if this covers it for now.

**Comment by LeLocTai** [comment]
I think this is ok.  Thank you for sharing such a wonderful library :)
