### ISSUE TITLE
Server is unable to prevent players from connecting, and unable to drop existing connections

### ISSUE THREAD

**Issue by g-klein** [BeardedManStudios/ForgeNetworkingRemastered#141]
### Version Number and Operating System(s):
Windows + latest forge

### Expected behavior:
If the server calls `((IServer)NetworkManager.Instance.Networker).Disconnect(player, `true);`, the specified player should be disconnected.  If the maximum players for the server has been reached, new connections should not be allowed.  If the 

### Actual behavior:
I have tried to set up a server with the max connections of 5.  When another client beyond the limit tries to join, all existing clients lose their connection, and the new joining client connects succesfully after a long delay.  Additional clients who try to join cannot.

I then tried raising the max number of connections to 15, and I tried manually using `((IServer)NetworkManager.Instance.Networker).StopAcceptingConnections();` when the desired maximum connections have been made (by calling `StopAcceptedConnections` in the `playerAccepted` event when `NetworkManager.Instance.Networker.ServerPlayerCounter > 4`).  However, the same behavior where, after the connection limit is hit, new connecting players will ruin the connection of existing players.

Finally, I tried using `((IServer)NetworkManager.Instance.Networker).Disconnect(player, `true);` in the `playerConnected` or `playerAccepted` event for players who connect after the limit is reached. (Again, this limit was determined using NetworkManager.Instance.Networker.ServerPlayerCounter > 4, it was not done using the server's max connection parameter).  This seemingly does not disconnect the incoming player if a limit was reached.  This seemed to do nothing -- incoming players could still connect with no problem even if the player limit was reached.

### Steps to reproduce:
There's a lot going on but I will gladly help you try to reproduce the issue.

**Comment by phalasz** [comment]
@g-klein would you be able to check that fix #217 resolves this issue?

**Comment by phalasz** [comment]
Can someone with the powers close this issue? There were no more reports of this and the ticket has been open for quite some time now with a fix merged.
