### ISSUE TITLE
NAT server not refreshing hosts

### ISSUE THREAD

**Issue by kojonek2** [BeardedManStudios/ForgeNetworkingRemastered#145]
### Version Number and Operating System(s):
Newest repo and windows 10

### Expected behavior:
Host should be registered on nat server every time he wants to be registered

### Actual behavior:
NatServer never deletes info about host and it doesn't allow to refresh this info so it works only for first attempt to host a server by player. I made dummy hotfix which allows to refresh info. Simply when it detects that this host is already registered, it removes old data and doesn't return from function.

### Steps to reproduce:
Run NetHolePunch.exe host server 2 times one after other from this same PC. When you host game second time you won't receive nat hole puch requests. 

#### [Optional] Discord Username:
kojonek2

**Comment by kojonek2** [comment]
@phalasz As I remember when you host game again on the same port the NetworkingPlayer changes and should be replaced to new connection instance. I may be wrong because I haven't used it since then.

**Comment by phalasz** [comment]
Is this still an issue? Can the ticket be closed?
