### ISSUE TITLE
NCW won't open

### ISSUE THREAD

**Issue by konstantin890** [BeardedManStudios/ForgeNetworkingRemastered#146]
### Version Number and Operating System(s):
Windows 10 x64, Unity 2018.1 Beta 13

### Expected behavior:
NCW to open

### Actual behavior:
NCW won't open

### Steps to reproduce:
Put any file (script, text file, etc.) in the user-generated folder. And NCW won't open anymore until you move/remove them.

#### [Optional] Discord Username:
Kosio#9955

**Comment by mcguinnessdr** [comment]
Putting non generated files in the generated folder will cause errors, this is expected behavior.
