### ISSUE TITLE
ConsoleTestProgram send text, receive wrong data

### ISSUE THREAD

**Issue by hideohiro** [BeardedManStudios/ForgeNetworkingRemastered#151]
### Steps to reproduce: run project test
- Open ConsoleTestProgram project, build.
- Run project and select "server"
- Open file ConsoleTestProgram.exe, choose client,
- Client send text "Hello"
- Server receive "Hello?"

**Comment by hideohiro** [comment]
I found the reason why the text receive always wrong. Uncomment line 172, file /BeardedManStudios/Source/Forge/Networking/Frame/FrameStream.cs to resolve it. I don't know why someone comment it. Hope this help!

**Comment by mcguinnessdr** [comment]
I believe #189 fixed this.
