### ISSUE TITLE
NCW RPC naming

### ISSUE THREAD

**Issue by devandart** [BeardedManStudios/ForgeNetworkingRemastered#152]
### Version Number and Operating System(s):
release-0.004, Windows 10 64 Bit

### Expected behavior:
Save and Show all RPC methods in the NCW dialog

### Actual behavior:
When the RPC name ends with "Changed" like "MyPropertyChanged" it gets removed in the ForgeClassObject.cs class because of internal field naming.
After saving again it gets lost.

### Steps to reproduce:
Create a NCW Object, Add a RPC called "GameChanged", Save&Compile, reopen NCW.

#### [Optional] Discord Username:
devandart

**Comment by phalasz** [comment]
Can this be closed now as there was a fix merged in to resolve this issue?

**Comment by phalasz** [comment]
Closing as a fix has been provided.
