### ISSUE TITLE
在场景加载完毕，调用NetworkManager:SceneReady的时候 NetworkObjectFactory在MainThreadManager中创建的NetworkObject并没有执行

### ISSUE THREAD

**Issue by wp498930275** [BeardedManStudios/ForgeNetworkingRemastered#160]
### Version Number and Operating System(s):
windows 10, unity3d

### Expected behavior:
no error

### Actual behavior:
sometimes NetworkBehavior.networkObject is null
NetworkObjectFactory create NetworkObject after SceneReady is called, because this execute in MainThreadManager.

### Steps to reproduce:
http://docs.forgepowered.com/GettingStarted/basic-moving-cube-example/
this example sometimes can cause this bug

**Comment by OptimisticQuan** [comment]
这个问题？
http://docs.forgepowered.com/GettingStarted/basic-moving-cube-example/#troubleshooting

**Comment by NFMynster** [comment]
Could you try and elaborate a bit more, and keep it in English? Then it's a easier to understand your issue and hopefully get it fixed.

**Comment by wp498930275** [comment]
就是空引用的问题，我和那个例子几乎一样，我多了个切换场景的操作，连接成功之后，在服务器上点击一个按钮，切换到下一个场景，其他的和例子里面完全一样。标题里是我查到的原因。  有一个很操蛋的修复方法，在NetworkManager:OnLevelFinishedLoading的SceneReady方法之前把 MainThreadManager里面的Actions都执行了 @OptimisticQuan

**Comment by phalasz** [comment]
Is this still an issue? Can this be closed?
