### ISSUE TITLE
Issues with Unity 2018.2

### ISSUE THREAD

**Issue by OnlyHardOfficial** [BeardedManStudios/ForgeNetworkingRemastered#168]
### Version Number and Operating System(s):
Windows 10 Enterprise

### Expected behavior:
I was hoping to open the solution without getting any initial error

### Actual behavior:
It shows that it is impossible to compile the solution in Visual Studio 2017 because it shows an error, and it is also impossible to open the project in Unity says two files not found!

**Comment by sommerper** [comment]
I don't have that error (2018.2.0f1). I've tried both the nightly version and 24.3 from the asset store.

**Comment by mcguinnessdr** [comment]
Cannot reproduce, many people are using Forge just fine with 2018.2.
