### ISSUE TITLE
NetworkDiscovery Android + Win Editor

### ISSUE THREAD

**Issue by lb4business** [BeardedManStudios/ForgeNetworkingRemastered#17]
FNR 23.02, Win7 64, Unity 5.6
Editor can't find server on android device and vice versa. But editor can find server on win build running on the same machine and 2 android devices can find each other

**Comment by baflink** [comment]
Can we get a separate issue opened up for the second issue listed here so that we can track/fix them independently?

**Comment by lb4business** [comment]
@baflink of course. Done :)

**Comment by theWill** [comment]
@lb4business can you retest with the latest develop branch. I think this issue is resolved now.

**Comment by lb4business** [comment]
@theWill Hi! I'll try to test it untille the end of the week

**Comment by lb4business** [comment]
@theWill i'm sorry, forgot to test it last week. Seems to work ok now. Thank you!
