### ISSUE TITLE
Can't deploy on Hololens - ReferenceRewriter errors

### ISSUE THREAD

**Issue by FireDragonGameStudio** [BeardedManStudios/ForgeNetworkingRemastered#171]
### Version Number and Operating System(s):
OS: Windows 10 x64 
Asset-Version: 24.3 - Latest version from Unity AssetStore
Unity-Version: 2018.1.6f1

### Expected behavior:
Building a simple networking prototype (basic cube moving example from docs) and deploy it to Hololens to check networking performance. Should at least start. No additional 3rd party libraries (e.g. Holotoolkit) used.

### Actual behavior:
Building the VisualStudio solution works somehow (with 171 errors regarding ReferenceRewriter and using for Non-UWP namespaces.

### Steps to reproduce:
Try the example from the docs and deploy it to Hololens (emulator or real device).

Best regards :)

**Comment by NFMynster** [comment]
You're saying you are using the asset store version, but actual behavior is to build the visual studio solution?
What exactly are your issue? :)
Join the Discord for better help btw.

**Comment by FireDragonGameStudio** [comment]
Hy @NFMynster,
when you create a Unity application for Hololens, it is necessary to build it as UWP app. This UWP build process fails with about 171 errors. The result of this building process is a visual studio solution which is used to deploy the app to Hololens (similar to the iOS build process in Unity).

The issue is, that the build for UWP throws a lot of "ReferenceRewriter" errors in Unity. I guess this is due to limited UWP support. As a result a can't use Forge Networking Remastered as networking solution and have to stick to UNET.

Best regards :)

**Comment by NFMynster** [comment]
Are these the errors you've been getting? https://github.com/BeardedManStudios/ForgeNetworkingRemastered/issues/39

**Comment by FireDragonGameStudio** [comment]
Unfortunately these are not the errors I get. I'll attach a screenshot for additional information.
![forgenetworkingerrors](https://user-images.githubusercontent.com/23502690/44021019-00cd5a42-9ee4-11e8-8167-8a2d07a7da3d.jpg)
