### ISSUE TITLE
Single run NetworkDiscovery issue

### ISSUE THREAD

**Issue by lb4business** [BeardedManStudios/ForgeNetworkingRemastered#18]
FNR 23.02, Win7 64, Unity 5.6
After disconnect editor can't find server on win build running on the same machine again, same problem with 2 android devices. After restarting the game the problem disapears, so NetworkDiscovery works just one time.

**Comment by theWill** [comment]
yep, experienced this exact bug

my details:
Lan discover bug - works on launch fine - when client disconnects from any server (keeping the application open) and go back to my menu screen to try to search and find another host (no results are returned). I tried reregistering the event but no luck. Relaunching the application and it works as expected.

**Comment by baflink** [comment]
Should be resolved with this commit:  https://github.com/BeardedManStudios/ForgeNetworkingRemastered/commit/0946b50ddfc17e9276fdcd254391cd90a18c758a
