### ISSUE TITLE
NCW Interpolation attribute won't stay checked, some fields gets interpolation even when uchecked

### ISSUE THREAD

**Issue by honda2** [BeardedManStudios/ForgeNetworkingRemastered#196]
### Version Number and Operating System(s):
03/10/2018-19.53.38,04 
Unity 2018.2.10f1
Windows 10 x64
**Czech cs-CZ locale**

### Expected behavior:
create PlayerNetworkObject
field position Vector3, checked Interpolate 0,1
field id Uint 
clicked Compile

have interpolated position and bare id property

### Actual behavior:
have interpolated both fields in code, but when opened NCW, no interpolate checked

### Steps to reproduce:
reproducable in vanilla example project, or with tidied generated classes to bare minimum, with steps provided in Expected Behavior

### Found solution
The problem is in Culture Info or whatewer Unity uses to treat (float).ToString() .
In my locale, there is comma used as decimal separator, witch is apparently used a s separator in JSON array in your GeneratedInterpol Attribute.

ForgeNetworkingEditor.cs:755

if (i + 1 < btn.ClassVariables.Count)
     interpolateValues += btn.ClassVariables[i].InterpolateValue.ToString().Replace(",", ".") + ",";
else
     interpolateValues += btn.ClassVariables[i].InterpolateValue.ToString().Replace(",", ".");

 will do, but some prettier JSON serialization would be desirable :)

**Comment by WhelanB** [comment]
This should be fixed in #198, if you'd like to validate the changes

**Comment by phalasz** [comment]
@honda2 is this still an issue or has the fix resolved it for you?

**Comment by phalasz** [comment]
Closing as a fix has been provided.
