### ISSUE TITLE
Problematic order of events NetworkStart and OwnerChanged

### ISSUE THREAD

**Issue by Effestiar** [BeardedManStudios/ForgeNetworkingRemastered#202]
### Version Number and Operating System(s):

- October 11 2018 18:03:38	
- Fresh Unity project
- Windows 10 64bit
- Unity 2018.1.3f1

### Expected behavior:
Being able to assign ownership right after creation of an object and being able to cleanly subscribe to this change. 
### Actual behavior:
There is no clean way of doing so if the object is spawned on the server.
On the server the OwnershipChanged event is called before NetworkStart.
On the client the NetworkStart is called before OwnershipChanged.

(As an extra point that ties in to this: It would be rather nice if ownership could be set during creation so we aren't dependent on ownershipchange events in the first place for initial setups. This way we could reliably use IsOwner during NetworkStart regardless of whether it was the server that spawned the object or not.)

Ownership from client to server wasn't tested and may be working as intended.

### Steps to reproduce:
Server
```cs
private void OnPlayerAccepted(NetworkingPlayer nPlayer, NetWorker sender)
    {
        MainThreadManager.Run(() =>
        {
            WaitingRoomPlayer wPlayer = NetworkManager.Instance.InstantiateWaitingRoomPlayer().GetComponent<WaitingRoomPlayer>();
            wPlayer.networkObject.AssignOwnership(nPlayer);
        });
```

Inside WaitingRoomPlayer
   ```cs
protected override void NetworkStart()
    {
        base.NetworkStart();
        networkObject.ownershipChanged += OnOwnershipChange;
    }
```
   ```cs
 private void OnOwnershipChange(NetWorker sender)
    {
        MainThreadManager.Run(() =>
        {
            Debug.Log("Test");
        });
    }
```
#### [Optional] Discord Username:
Effestiar#1208

**Comment by phalasz** [comment]
From @Adrian_H#1701 on Discord:

> @NFMynster I have tested the PR https://github.com/BeardedManStudios/ForgeNetworkingRemastered/pull/204
> It fixes the issue I had and also solves the issue 202 https://github.com/BeardedManStudios/ForgeNetworkingRemastered/issues/202
> 
> The event that is set up in the NetworkStart
> networkObject.ownershipChanged += OnOwnershipChange; 
> gets called on the client and as a result outputs "Test". This happens only on the client that received the ownership, not on any other connected clients.

**Comment by adrianhoppe** [comment]
Yeah, thanks @phalasz
This issue can be closed, as the error no longer appears after the fix.
PR #204 is already merged into master.
