### ISSUE TITLE
NetworkBehaviors awaiting NetworkBind() indefinetly and not being destroyed on the client

### ISSUE THREAD

**Issue by k77torpedo** [BeardedManStudios/ForgeNetworkingRemastered#203]
### Version Number and Operating System(s):
* Unity Version 2018.2.1f1
* Forge Package Downloaded 2018-11-28
* Fresh Unity Project
* Windows 7 64bit

### Expected behavior:
1) A NetworkBehavior is placed in a Scene when in the Unity-Editor (not during runtime). 
2) The Server is started and the NetworkBehavior is properly registered and initialized on the server. 
3) A Client connects and the Scene with the NetworkBehavior is also loaded and awaits NetworkBehavior.NetworkBind() which it shortly gets from the Server.
4) The Server destroys the NetworkBehavior and the NetworkBehavior on the Client is also destroyed.
5) Another Client connects and the NetworkBehavior from the Scene awaits NetworkBehavior.NetworkBind(). As the NetworkBehavior has been previously destroyed on the Server the NetworkBehavior.NetworkBind() will fail and the NetworkBehavior will be destroyed. 

### Actual behavior:
5) Another Client connects and the NetworkBehavior from the Client-Scene awaits NetworkBehavior.NetworkBind(). The NetworkBehavior will remain unbound in the Scene for an indefinite amount of time as it can't be bound to the already destroyed NetworkBehavior on the server. The NetworkBehavior will remain dead in the Client-Scene without any way to be identified as "already destroyed on the server".

### Proposed Solution:
Create a NetworkObject.bindfailure-Event similar to the Networker.bindfailure-Event to notify any listeners that this NetworkObject can't currently be bound to the Server - either because the respective Networker has no connection, a timeout has been reached or the NetworkObject has already been destroyed on the Server. 

### Steps to reproduce:
A full project displaying the behavior can be seen below:
[Forge Bug Test.zip](https://github.com/BeardedManStudios/ForgeNetworkingRemastered/files/2624954/Forge.Bug.Test.zip)

#### [Optional] Discord Username:
k77torpedo

**Comment by phalasz** [comment]
In my tests code execution on the late joining client won't even get to NetworkBind.

In `NetworkManager.SceneReady` if calls `NetworkObject.Flush` but the list of pending network objects is 0 so nothing willl happen and the behaviour will be stuck in the pending behaviour list.

This is on latest develop branch.

**Comment by phalasz** [comment]
@k77torpedo would you be able to check that the fix in the linked PR fixes the issue for you?

**Comment by EvgenNechyporuk** [comment]
PR solved the problem! It works correctly. Thank you very much!

**Comment by k77torpedo** [comment]
@phalasz yea in the example attached the issue has now been resolved. When the server has deleted a NetworkBehavior that has been placed inside the scene via the Unity-Editor and another client connects the NetworkBehavior on the client will now be properly deleted! Awesome thank you! :)

I unexpectedly had to hit the road yesterday so I can't make a PR myself but 2 suggestions: initialize the list with the proper capacity and using the _Values_-collection in the foreach-loop like below:
```
List<GameObject> objetsToDestroy = new List<GameObject>(pendingObjects.Count);
foreach (var kvp in pendingObjects.Values)
{
	var gameObject = ((NetworkBehavior) kvp).gameObject;
	if (!objetsToDestroy.Contains(gameObject))
		objetsToDestroy.Add(gameObject);
}
```

Thanks again for the fix!

**Comment by phalasz** [comment]
Awesome. I'll PR your suggestions.

**Comment by phalasz** [comment]
@k77torpedo I've added a new PR with the above proposed changes.

**Comment by NFMynster** [comment]
@k77torpedo can you retest this?
Ah well, seems the fix is confirmed, lemme know and I'll close this issue

**Comment by phalasz** [comment]
Fix has been merge and no further activity. Closing issue.

**Comment by PyeonggukLee** [comment]
For me, patching this commit destroyed the networked game objects in a scene, so I reverted this commit from our dev repo.

**Comment by phalasz** [comment]
Would you be able to provide more information on this? Ideally with a small project that reproduces the issue?
