### ISSUE TITLE
[Solved] Server doesn't show up after changing master Server Data

### ISSUE THREAD

**Issue by CoreyHUN** [BeardedManStudios/ForgeNetworkingRemastered#230]
### Version Number and Operating System(s):
27.01.19-20:00:44,13
Windows 10 (v.1809)
### Expected behavior:
Show server in the Server Browser

### Actual behavior:
Server doesn't show up.
Code stops at ServerBrowser.cs > Line 92

### Steps to reproduce:
Change the master server data after MultiplayerMenu.cs >Line 200

**Comment by phalasz** [comment]
Discord username: @Corey#7494

**Comment by phalasz** [comment]
Could you provide more detail please?
Does the server show up on the master server's command line output?

MultiplayerMenu.cs line 217 is a `{`. (https://github.com/BeardedManStudios/ForgeNetworkingRemastered/blob/7fd06aaf8f937074f9b593091ce05c5cf5d13498/Forge%20Networking%20Remastered%20Unity/Assets/Bearded%20Man%20Studios%20Inc/Scripts/Multiplayer%20Menu/MultiplayerMenu.cs#L217)

**Comment by phalasz** [comment]
Have you updated `ServerBrowser.cs` on line 16 to match the gameid to the above serverId you set?
The master server will only return hosts that have the same id.

**Comment by CoreyHUN** [comment]
Nope, i did not! Thanks, that was the problem.
