### ISSUE TITLE
Multiplayer Menu ip address hard to read while typing

### ISSUE THREAD

**Issue by AttackingHobo** [BeardedManStudios/ForgeNetworkingRemastered#234]
### Expected behavior:
I click into the text box, I see the current text with enough contrast from the input field box to see what I'm typing

### Actual behavior:
I click the text box, the box gets highlighted near white, with white text on top. I have to blindly type the IP address

Potential Fix. Change the color of the highlight color, or the text file.

#### Discord Username:
AttackingHobo

**Comment by mcguinnessdr** [comment]
The multiplayer menu is just an example you can modify or replace depending on your needs.  If you're not happy with the color of the text you can just change it to what you prefer.
