### ISSUE TITLE
In scene network objects are not initialized correctly when calling NetworkObject.Flush

### ISSUE THREAD

**Issue by phalasz** [BeardedManStudios/ForgeNetworkingRemastered#235]
Issue created from a bug report in #forge-bugs on discord
### Version Number and Operating System(s):
Forge Version 11.02.2019 master

### Expected behavior:
When automatic scenes is disabled and switching scenes. On scene load calling flush should initialize all network objects that are already in the scene.

### Actual behavior:
Automatic Scenes is disabled in Forge's NetworkManager. I start a server, load a scene upon server creation, then call NetworkObject.Flush. NetworkObjects already contained in the second scene will not Initialize.
Reproduction Steps:

### Steps to reproduce:
Open my example project, open mainMenu.unity, hit play, click the "Server"  button, the next scene will load, a Debug.Log should be playing from inside ExistingObject.cs, but does not. If you enable Automatic Scenes, and comment out line 114 in SpherakillNetworkManager.cs, the Debug.Log will fire due to Forge's internal scene loaded callback being fired.

Example project:
https://www.dropbox.com/s/9wdlz4zr6zccr0i/forgeFlushBug.unitypackage?dl=0

#### [Optional] Discord Username:
 @ambientocclusion#7740

**Comment by phalasz** [comment]
Seems to be not a bug. For in scene network objects the custom setup code will need to find and initialize all in scene NetworkBehaviors before calling Flush.

Not sure if something similar will need to be done on the client side as the example code provided only has server code.

**Comment by ambocclusion** [comment]
I would love for NetworkManager.OnLevelFinishedLoading or NetworkManager.SceneReady to be exposed as public so I can rely on Forge's built in commands to ensure the scene is initialized properly for now and every future Forge release.

**Comment by phalasz** [comment]
I guess the changes made to the NetworkManager in #236 are enough to make this work on custom solutions as the `SceneReady` can now be called as access to it has been changed.
