### ISSUE TITLE
Need to know number of players connected at same time

### ISSUE THREAD

**Issue by RYG81** [BeardedManStudios/ForgeNetworkingRemastered#245]
Sorry my question is little general
I just want to know how many players can be connected to a single server at the same time? My game is not a big environment where we have to calculate transforms of all players and sync. It's more like a simple screen with lots of sliders and game objects where a player just need to get updates of different values related to those game objects and sliders and text. All player receive the same update so an update of data is one once (every time server does it).
For example, I have a heart beating in the view with its slider for the speed of heartbeats is on screen. Server/maser changes slider and depending on changes heartbeats changes which should be updated in all player views same time.
Is it possible to have 50+ player same time? Please answer it, it will be a great help to start with Forge Networking ReMastered.

**Comment by NFMynster** [comment]
Please join the Discord, where all support happens! You can find the link in the read me.

**Comment by RYG81** [comment]
ok. I joined and put my question on discord.
Hope to get some help asap.
