### ISSUE TITLE
7 warnings

### ISSUE THREAD

**Issue by scc172fly** [BeardedManStudios/ForgeNetworkingRemastered#246]
Hello, the project has made better progress during this period of time. I am very optimistic about this project, and I am using it to make my game. However, I am more ocd, source code imported into Unity there are 7 warnings. Thank you for this great project.

**Comment by NFMynster** [comment]
Hello, I only get a single one, which warnings are we talking about?

**Comment by Crazy8ball** [comment]
Latest of master should have no more warnings. Please open this if you have them showing up again.
