### ISSUE TITLE
Sending Array in RPC Forge

### ISSUE THREAD

**Issue by smkplus** [BeardedManStudios/ForgeNetworkingRemastered#256]
How can I send array in forge?
for example I need Vector3[ ] 
![unknown](https://user-images.githubusercontent.com/16706911/56075009-df278280-5dd0-11e9-9c40-eb33a1847626.png)

**Comment by NFMynster** [comment]
Make it a serializable class and serialize it into a byte array. You can join the Forge Discord for help and support incase

**Comment by smkplus** [comment]
@NFMynster this is mean I shouldn't send vector3 array inside network? how can I convert vector3[ ] to byte[] ?
