### ISSUE TITLE
BMSByte array length differs from length of input byte array.

### ISSUE THREAD

**Issue by julienkay** [BeardedManStudios/ForgeNetworkingRemastered#260]
### Version Number and Operating System(s):
v26 (latest Asset Store version) - Windows 10 64bit

### Expected behavior:
When creating a BMSByte using Clone() or Append() the resulting byteArr in the BSMByte object should have the same length as the data that was passed into the Clone() or Append() method.

### Actual behavior:
The resulting byteArr is actually 1 byte larger.

### Steps to reproduce:
```
byte[] testInput = new byte[10];
BMSByte forgeByteArray = new BMSByte();
forgeByteArray.Clone(testInput);
Debug.Assert(forgeByteArray.byteArr.Length == testInput.Length,
    "BSMByte has a different length compared to the input data. " +
    "Actual Value " + forgeByteArray.byteArr.Length +
    ". Expected value: " + testInput.Length);
```

#### [Optional] Discord Username:
julien_kay

**Comment by phalasz** [comment]
@julienkay what does `forgeByteArray.Size` say?

The +1 is to make sure the internal buffer is large enough to put the input array into whe the internal size is smaller then the input array lenght.

If you were to do 
```cs
forgeByteArray.SetSize(testInput.Length);
forgeByteArray.Clone(testInput);
```
Then `forgeByteArray.CompressBytes().Length` should be the same as `testInput.Length`
