### ISSUE TITLE
il2cpp error

### ISSUE THREAD

**Issue by uneedtee** [BeardedManStudios/ForgeNetworkingRemastered#267]
### Version Number and Operating System(s):

Windows 10, Unity3D  2018.3.14f1, Forge Version 03/10/2018 19.53.38,04

### Expected behavior:

Should build with il2cpp

### Actual behavior:

Exception ... il2cpp did not run properly!

### Steps to reproduce:

Create New Empty Project with Unity
Add Forge from Asset Store (or GitHub, same error)
Open scene MultiPlayerMenu
Alter ProjectSettings including ScriptingBackend IL2CPP
Build

It used to work with former versions that way, do i miss something?

**Comment by NFMynster** [comment]
What errors are you receiving? Remove your TCP websockets file and it should be good.

**Comment by uneedtee** [comment]
Thank you, removing TCP websockets file helped. Was that behavior already mentioned before? Found topics only relating to webgl builds, but i was building for android. Thx again!
