### ISSUE TITLE
We have no option to send a client -> server packet without using low-level api buffers

### ISSUE THREAD

**Issue by spectre69** [BeardedManStudios/ForgeNetworkingRemastered#27]
### Version Number and Operating System(s)
Remastered
### Expected behavior
  NetworkManager.client.connection.Send(UnetGameRoom.AccessMsgType, new StringMessage(access.Token));
### Actual behavior
None
### Steps to reproduce
7 years of network programming

**Comment by baflink** [comment]
See @kamyker's PR above for more information
