### ISSUE TITLE
InvalidCastException: Specified cast is not valid. when connection through Steam

### ISSUE THREAD

**Issue by EvgenNechyporuk** [BeardedManStudios/ForgeNetworkingRemastered#274]
### Version Number and Operating System(s):
03/10/2018-19.53.38,04  Windows 10 64bit

### Actual behavior:
When the initial connection through Steam, get many of the same errors on each network object.

InvalidCastException: Specified cast is not valid.
BeardedManStudios.Forge.Networking.NetworkObject..ctor (BeardedManStudios.Forge.Networking.NetWorker networker, System.UInt32 serverId, BeardedManStudios.Forge.Networking.Frame.FrameStream frame) (at Assets/Bearded Man Studios Inc/Scripts/Networking/Forge/Networking/Objects/NetworkObject.cs:478)
BeardedManStudios.Forge.Networking.Generated.GameManagerNetworkObject..ctor (BeardedManStudios.Forge.Networking.NetWorker networker, System.UInt32 serverId, BeardedManStudios.Forge.Networking.Frame.FrameStream frame) (at Assets/Bearded Man Studios Inc/Generated/UserGenerated/GameManagerNetworkObject.cs:80)
BeardedManStudios.Forge.Networking.Generated.NetworkObjectFactory+<>c__DisplayClass0_0.<NetworkCreateObject>b__0 () (at Assets/Bearded Man Studios Inc/Generated/NetworkObjectFactory.cs:32)
BeardedManStudios.Forge.Networking.Unity.MainThreadManager.HandleActions (BeardedManStudios.Forge.Networking.Unity.MainThreadManager+UpdateType updateType) (at Assets/Bearded Man Studios Inc/Scripts/MainThreadManager.cs:165)
BeardedManStudios.Forge.Networking.Unity.MainThreadManager.FixedUpdate () (at Assets/Bearded Man Studios Inc/Scripts/MainThreadManager.cs:171)

### I solved the error like this:
Replaced line 475 in Bearded Man Studios Inc/Scripts/Networking/Forge/Networking/Objects/NetworkObject.cs with this:

#if STEAMWORKS
                if (networker is SteamP2PClient)
                    ((SteamP2PClient)networker).Send(createdFrame, true);
                else if (networker is UDPClient)
#else
                if (networker is UDPClient)
#endif

#### Discord Username:
Evgen Nechyporuk#6745

**Comment by phalasz** [comment]
Could you create a PR for the solution as that was clearly missing from there where you put it.

**Comment by EvgenNechyporuk** [comment]
done

**Comment by phalasz** [comment]
Fix has been merged into `develop`
