### ISSUE TITLE
MasterServer params not working

### ISSUE THREAD

**Issue by GiviMAD** [BeardedManStudios/ForgeNetworkingRemastered#277]
I'm using latest master server build. I'm not able to configure the port passing command arguments. I think the check on Program.cs is wrong, it check if the arguments dictionary contains "port" but instead it should look for "-port" because the argument parse function doesn't seems to remove the "-" from the key 
### Expected" behavior:
Use provided port

### Actual behavior:
Use default port

### Steps to reproduce:
run MasterServer.exe passing arguments

**Comment by phalasz** [comment]
@GiviMAD we just merged a fix into the develop branch. Would you be able to check that command line arguments now work as expected?

**Comment by phalasz** [comment]
No response on ticket for a long time. Fix has been merged in.
