### ISSUE TITLE
Exception  triggered when leaving a server and reconnect to it

### ISSUE THREAD

**Issue by rayuthebest** [BeardedManStudios/ForgeNetworkingRemastered#282]
### Version Number and Operating System(s):
Library at Develop @26/05/2019
Windows 7
Unity version: 2017.4.27f1

### Expected behavior:
When a client leave a server and he rejoin after some minutes, game should be reload

### Actual behavior:
An exception is triggered on NetworkBehavior at ProcessOther method. Due to this exception, game is not loaded correctly.

### Steps to reproduce:
Server is created (UDP with NAT server)
Client join
Client leave the game (unload scene)
Client tries to join again without leaving the game (if client close & open the game, everything works fine)

#### Workaround

I replaced this line at "protected void ProcessOthers(Transform obj, ref uint idOffset)" @NetworkBehavior.cs:
            skipAttachIds.Add(idOffset++, components[i]);

By the next code:
            try
            {
               skipAttachIds.Add(idOffset++, components[i]);
            }
            catch (Exception e)
            {
               skipAttachIds.Remove(idOffset - 1);
               skipAttachIds.Add(idOffset - 1, components[i]);
            }

After the change, game is loaded correctly.

#### [Optional] Discord Username:
Sorry, I do not use Discord.

#### Exception triggered (extract of the log file)

Unloading 150 unused Assets to reduce memory usage. Loaded Objects now: 7338.
Total: 9.291127 ms (FindLiveObjects: 0.728615 ms CreateObjectMapping: 0.160820 ms MarkObjects: 7.894066 ms  DeleteObjects: 0.506530 ms)

Unloading 4 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 135.680438 ms

Unloading 5116 unused Assets to reduce memory usage. Loaded Objects now: 2983.
Total: 20.750598 ms (FindLiveObjects: 0.539350 ms CreateObjectMapping: 0.398951 ms MarkObjects: 7.843012 ms  DeleteObjects: 11.969282 ms)

Unloading 5 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 3.100081 ms
ArgumentException: An element with the same key already exists in the dictionary.
  at System.Collections.Generic.Dictionary`2[System.UInt32,BeardedManStudios.Forge.Networking.Unity.NetworkBehavior].Add (UInt32 key, BeardedManStudios.Forge.Networking.Unity.NetworkBehavior value) [0x00000] in <filename unknown>:0 
  at BeardedManStudios.Forge.Networking.Unity.NetworkBehavior.ProcessOthers (UnityEngine.Transform obj, System.UInt32& idOffset) [0x00000] in <filename unknown>:0 
  at BeardedManStudios.Forge.Networking.Unity.NetworkBehavior.ProcessOthers (UnityEngine.Transform obj, System.UInt32& idOffset) [0x00000] in <filename unknown>:0 
  at BeardedManStudios.Forge.Networking.Generated.ChatMSGBehavior.Initialize (BeardedManStudios.Forge.Networking.NetworkObject obj) [0x00000] in <filename unknown>:0 
  at BeardedManStudios.Forge.Networking.Unity.NetworkManager.CreatePendingObjects (BeardedManStudios.Forge.Networking.NetworkObject obj) [0x00000] in <filename unknown>:0 
  at (wrapper delegate-invoke) BeardedManStudios.Forge.Networking.NetworkObject/NetworkObjectEvent:invoke_void__this___NetworkObject (BeardedManStudios.Forge.Networking.NetworkObject)
  at BeardedManStudios.Forge.Networking.NetWorker.OnObjectCreated (BeardedManStudios.Forge.Networking.NetworkObject target) [0x00000] in <filename unknown>:0 
  at BeardedManStudios.Forge.Networking.NetworkObject.Flush (BeardedManStudios.Forge.Networking.NetWorker target, System.Collections.Generic.List`1 remainingScenesToLoad, BeardedManStudios.Forge.Networking.NetworkObjectEvent objectCreatedHandler) [0x00000] in <filename unknown>:0 
  at BeardedManStudios.Forge.Networking.Unity.NetworkManager.SceneReady (Scene scene, LoadSceneMode mode) [0x00000] in <filename unknown>:0 
  at UnityEngine.SceneManagement.SceneManager.Internal_SceneLoaded (Scene scene, LoadSceneMode mode) [0x00000] in <filename unknown>:0

**Comment by phalasz** [comment]
You need to properly disconnect your client by using NetworkManager.Disconnect()

**Comment by rayuthebest** [comment]
Hi, I tried it but it does not work.

I got the next method on my NetworkManager:


```
   public static void Disconnect()
   {
      if (game_client != null)
         game_client.Disconnect(true);

      if (game_server != null)
         game_server.Disconnect(true);

      if (mgr != null)
      {
         mgr.Disconnect();
      }

      game_client = null;
      game_server = null;

      SceneManager.LoadScene("MainMenu", LoadSceneMode.Single);
   }
```

And I call it when player press on the "Go to Main Menu" Button:

```
public void backToMainMenu()
   {
      ForgeNetwork.Disconnect();
   }
```

**Comment by phalasz** [comment]
Without seeing your code it is hard to tell what is wrong. From the comments it seems that you are making custom functionality that is not from Forge itself and you are getting issues because of that.

The easiest would be for you to join our discord where you could get more immediate help from the community.

**Comment by rayuthebest** [comment]
Here is the code that I customized respect to the provided example.

Of course, I have set some RPC method for my game (using the wizard), but I have not modified the generated code, so I believe that the problem is at this class.

Bassically, I am trying to make a wraparound of your NetworkManager class, merging on a common point all functionality related with the Server & Clients.

Sorry to send you the code in this way, but it is the best way that I have found

> using BeardedManStudios.Forge.Networking;
> using BeardedManStudios.Forge.Networking.Unity;
> using BeardedManStudios.Forge.Networking.Lobby;
> using BeardedManStudios.SimpleJSON;
> using System.Collections.Generic;
> using UnityEngine;
> using UnityEngine.SceneManagement;
> using UnityEngine.UI;
> 
> public class ForgeNetwork : MonoBehaviour
> {
>    private const string ServerGameID = "DemonsAndDice";
>    private const string ServerAddress = "ServerAddress";
>    private const ushort hostServerPort = 15938;
>    private const ushort masterServerPort = 15940;
>    private const ushort natServerPort = 15941;
> 
>    public bool DontChangeSceneOnConnect = false;
> 
>    public GameObject networkManager = null;
>    private static NetworkManager mgr = null;
>    
>    private bool _matchmaking = false;
>    public bool useMainThreadManagerForRPCs = true;
> 
>    public GameObject loadingPanel_prefab;
>    private LoadingGamePanel loadingPanel;
> 
>    private static UDPClient game_client = null;
>    private static UDPServer game_server = null;
> 
>    public static void Disconnect()
>    {
>       if (game_client != null)
>          game_client.Disconnect(true);
> 
>       if (game_server != null)
>          game_server.Disconnect(true);
> 
>       if (mgr != null)
>       {
>          mgr.Disconnect();
>       }
> 
>       game_client = null;
>       game_server = null;
> 
>       SceneManager.LoadScene("MainMenu", LoadSceneMode.Single);
>    }
> 
>    private void showLoadingPanel(Game_DB game, bool host)
>    {
>       GameObject canvas = GameObject.FindWithTag("canvas");
>       GameObject loadingPanel_i = Instantiate(loadingPanel_prefab, canvas.transform);
>       loadingPanel = loadingPanel_i.GetComponent<LoadingGamePanel>();
>       loadingPanel.updatePanel(game, host);
>    }
> 
>    private void Start()
>    {
>       NetWorker.PingForFirewall(masterServerPort);
> 	  
>       if (useMainThreadManagerForRPCs)
>          Rpc.MainThreadRunner = MainThreadManager.Instance;
>    }
> 
>    private void LocalServerLocated(NetWorker.BroadcastEndpoints endpoint, NetWorker sender)
>    {
>       Debug.Log("Found endpoint: " + endpoint.Address + ":" + endpoint.Port);
>    }
> 
> 
>    public void Connect(Game_DB game)
>    {
>       if (_matchmaking)
>          return;
> 
>       showLoadingPanel(game, false);
> 
>       _matchmaking = true;
> 
>       if (mgr == null && networkManager == null)
>          throw new System.Exception("A network manager was not provided, this is required for the tons of fancy stuff");
> 
>       mgr = Instantiate(networkManager).GetComponent<NetworkManager>();
> 
>       mgr.MatchmakingServersFromMasterServer(ServerAddress, masterServerPort, 1, (response) =>
>       {
>          _matchmaking = false;
>          //Debug.LogFormat("Matching Server(s) count[{0}]", response.serverResponse.Count);
> 
>          if (response != null && response.serverResponse.Count > 0)
>          {
>             foreach (MasterServerResponse.Server server in response.serverResponse)
>             {
>                if (server.Name == game.Game_ID)
>                {
>                   //TCPClient client = new TCPClient();
>                   game_client = new UDPClient();
>                   if(MainPlayerInfo.debug)
>                      game_client.Connect("127.0.0.1", server.Port);
>                   else
>                      game_client.Connect(server.Address, server.Port, ServerAddress, natServerPort);
>                   Connected(game_client, game);
>                   return;
>                }
>             }
>          }
>          ModalWin.Info("Cannot connect to server: " + game.Game_name + "\n\nHas the game master launched the game?");
>          loadingPanel.HidePanel();
>       }, ServerGameID);
>       
>    }
> 
>    public void Host(Game_DB game)
>    {
>       showLoadingPanel(game, true);
>      
>       game_server = new UDPServer(64);
> 
>       if (MainPlayerInfo.debug)
>          ((UDPServer)game_server).Connect("127.0.0.1", hostServerPort);
>       else
>          ((UDPServer)game_server).Connect("127.0.0.1", hostServerPort, ServerAddress, natServerPort);
> 
>       game_server.playerTimeout += (player, sender) =>
>       {
>          Debug.Log("Player " + player.NetworkId + " timed out");
>       };
> 
>       Connected(game_server, game);
> 
>    }
> 
>    public void Connected(NetWorker networker, Game_DB game)
>    {
>       if (!networker.IsBound)
>       {
>          Debug.LogError("NetWorker failed to bind");
>          return;
>       }
> 
>       if (mgr == null && networkManager == null)
>       {
>          Debug.LogWarning("A network manager was not provided, generating a new one instead");
>          networkManager = new GameObject("Network Manager");
>          mgr = networkManager.AddComponent<NetworkManager>();
>       }
>       else if (mgr == null)
>          mgr = Instantiate(networkManager).GetComponent<NetworkManager>();
> 
>       // If we are using the master server we need to get the registration data
>       JSONNode masterServerData = null;
>       if (!string.IsNullOrEmpty(ServerAddress))
>       {
>          string serverId = ServerGameID;
>          string serverName = game.Game_ID;
>          string type = "Deathmatch";
>          string mode = "Teams";
>          string comment = "Demo comment...";
> 
>          masterServerData = mgr.MasterServerRegisterData(networker, serverId, serverName, type, mode, comment, false, 0);
>       }
> 
>       mgr.Initialize(networker, ServerAddress, masterServerPort, masterServerData);
> 
>       if (networker is IServer)
>       {
>          if (!DontChangeSceneOnConnect)
>             SceneManager.LoadScene(SceneManager.GetActiveScene().buildIndex + 1);
>          else
>             NetworkObject.Flush(networker); //Called because we are already in the correct scene!
>       }
>    }
> 
>    private void OnApplicationQuit()
>    {
>       Disconnect();
>    }
>    
>    public void Refresh()
>    {
>       // TODO:  Clear out any previously listed servers
> 
>       // The Master Server communicates over TCP
>       TCPMasterClient client = new TCPMasterClient();
> 
>       // Once this client has been accepted by the master server it should sent it's get request
>       client.serverAccepted += (a) =>
>       {
>          try
>          {
>             // The overall game id to select from
>             string gameId = ServerGameID;
> 
>             // The game type to choose from, if "any" then all types will be returned
>             string gameType = "any";
> 
>             // The game mode to choose from, if "all" then all game modes will be returned
>             string gameMode = "all";
> 
>             // Create the get request with the desired filters
>             JSONNode sendData = JSONNode.Parse("{}");
>             JSONClass getData = new JSONClass();
> 
>             // The id of the game to get
>             getData.Add("id", gameId);
>             getData.Add("type", gameType);
>             getData.Add("mode", gameMode);
> 
>             sendData.Add("get", getData);
> 
>             // Send the request to the server
>             client.Send(BeardedManStudios.Forge.Networking.Frame.Text.CreateFromString(client.Time.Timestep, sendData.ToString(), true, Receivers.Server, MessageGroupIds.MASTER_SERVER_GET, true));
>          }
>          catch
>          {
>             // If anything fails, then this client needs to be disconnected
>             client.Disconnect(true);
>             client = null;
>          }
>       };
> 
> 
>       // An event that is raised when the server responds with hosts
>       client.textMessageReceived += (player, frame, a) =>
>          {
>             try
>             {
>             // Get the list of hosts to iterate through from the frame payload
>             JSONNode data = JSONNode.Parse(frame.ToString());
>                if (data["hosts"] != null)
>                {
>                // Create a C# object for the response from the master server
>                MasterServerResponse response = new MasterServerResponse(data["hosts"].AsArray);
> 
>                   if (response != null && response.serverResponse.Count > 0)
>                   {
>                      // Go through all of the available hosts and add them to the server browser
>                      foreach (MasterServerResponse.Server server in response.serverResponse)
>                      {
>                         Debug.Log("Name: " + server.Name);
>                         Debug.Log("Address: " + server.Address);
>                         Debug.Log("Port: " + server.Port);
>                         Debug.Log("Comment: " + server.Comment);
>                         Debug.Log("Type: " + server.Type);
>                         Debug.Log("Mode: " + server.Mode);
>                         Debug.Log("Max Players: " + server.MaxPlayers);
>                         Debug.Log("Protocol: " + server.Protocol);
> 
>                      // TODO:  Update UI or something with the above data
>                      }
>                   }
>                }
>             }
>             finally
>             {
>                if (client != null)
>                {
>                   // If we succeed or fail the client needs to disconnect from the Master Server
>                   client.Disconnect(true);
>                   client = null;
>                }
>             }
>          };
> 
>       client.Connect(ServerAddress, masterServerPort);
>    }
> 
> }
> 
> >

**Comment by phalasz** [comment]
May I suggest sending huge chunks of code via pastebin/hastebin/gdl paste etc. Also help on our discord is usually quicker.

**Comment by phalasz** [comment]
Closing do to inactivity.
