### ISSUE TITLE
[NCW] Removing Argument from RPC swaps naming

### ISSUE THREAD

**Issue by Fashdey** [BeardedManStudios/ForgeNetworkingRemastered#29]
When using the Wizard for adding/editing RPCs
I've discovered that if you have multiple arguments, and remove one which has one underneath it, the name of the removed will overwrite the one underneath.

### Version Number and Operating System(s)
Newest Dev Branch
Build Date: (11/07-17)

### Expected behavior
Having an RPC with 3 Arguments

Arguments
Slot: Name [Type]
1: A [int]
2: B [Vector3]
3: C [Vector3]

Removing 1st results
1: B [Vector3]
2: C [Vector3]

### Actual behavior
Arguments
Slot: Name [Type]
1: A [int]
2: B [Vector3]
3: C [Vector3]

Removing 1st results
1: A [Vector3]
2: C [Vector3]

### Steps to reproduce
1. Make RPC
2. Add 3 different Arguments
3. Compile
4. Return to said RPC
5. Remove first Argument
6. Name of removed argument is passed to the next argument slot (Not altering the type)

**Comment by phalasz** [comment]
Is this still an issue? Can this be closed?

**Comment by NFMynster** [comment]
@Fashdey Still using Forge?

**Comment by Fashdey** [comment]
Haven't been using Forge for more than a year, so I can't tell.
