### ISSUE TITLE
Older Version of Unity - 5.5.4f1

### ISSUE THREAD

**Issue by Brainversation** [BeardedManStudios/ForgeNetworkingRemastered#293]
Hello,

I was hired to substitute Forge for another networking solution in an earlier version of Unity. I noticed on the Asset store that Forge requires Unity 2018.2.9 and the project I will be working on is in version 5.5.4f1.

I have imported the Nightly Master Branch package into a blank Unity 5.5.4f1 project and there aren't any errors so far and want to make sure that I am not missing any functionality that won't work in the future.

Thank you in advance for you help!

### Version Number and Operating System(s):
Windows 10

### Expected behavior:
Full functionality in older versions of Unity, such as 5.5.4f1

### Actual behavior:
Seems fine, but want to make sure.

**Comment by NFMynster** [comment]
You might miss out on some Steam implementation, as you probably are still using dotnet 3.5.
@phalasz - Steam is 4.x yeah?
Else, you should be all good. It would not compile or similar if you were missing out.

**Comment by Brainversation** [comment]
Thank you for your quick reply @NFMynster 

I didn't know about the Steam issue, but I think it should be fine. ( I will post here if I have any update on that )

I also just tested the "Basic Moving Cube Example" in the Getting started section and everything seems to be working.

Just wanted to make sure I wasn't missing anything.

Thank you again.

**Comment by NFMynster** [comment]
I would join the official Discord if I were you. Most support happens there and the reply times are faster.
But yeah, you should be all good.

**Comment by Brainversation** [comment]
Thank you again!
