### ISSUE TITLE
[Documentation] Contributing coding standards

### ISSUE THREAD

**Issue by Balroth** [BeardedManStudios/ForgeNetworkingRemastered#299]
Seeing this https://github.com/BeardedManStudios/ForgeNetworkingRemastered/blob/master/CONTRIBUTING.md
I just wanted to ask, what about single-line iteration statements?

```csharp
for (;;)
    Debug.Log("Infinite Loop");
```
or this applies?
```csharp
for (;;)
{
    Debug.Log("Infinite Loop");
}
```

@BrentFarris

**Comment by BrentFarris** [comment]
Thanks for asking. I would say that the second one is better because it relates to an infinite loop and infinite loops should be exceptionally clear to the reader. I will update the contributing document to mention while loops, do loops, and for(;;) loops to be code blocks.

**Comment by BrentFarris** [comment]
https://github.com/BeardedManStudios/ForgeNetworkingRemastered/commit/3e106b6d53966d4ac3b3490b277edc6696d12aeb
