### ISSUE TITLE
Visual Studio Builds do not work

### ISSUE THREAD

**Issue by j-santander** [BeardedManStudios/ForgeNetworkingRemastered#300]
### Version Number and Operating System(s):
git clone from master

Windows 10.
### Expected behavior:
Following the build instructions for "Git Source Code (Built)" in [Getting-Started](https://github.com/BeardedManStudios/ForgeNetworkingRemastered/wiki/Getting-Started#installation)

### Actual behavior:
The build fails, complaining about missing files in `ForgeNetworkingRemastered/BeardedManStudios/Source` (e.g. BMSByte.cs, ArgumentParser.cs, ....) 

because the files are really missing. They were removed with commit 4f5a0b9d3d3ec1f1cffd3dcd8f3680ce70dca9

I'm fairly new to all this, but please, either restore the files, or correct the build instructions.

### Steps to reproduce:
See above.

**Comment by phalasz** [comment]
We moved away from built dlls. Please use source directly.
Thanks for reminding me. I have now updated the wiki and remove the built dlls option from getting started.
