### ISSUE TITLE
Entering late to the session

### ISSUE THREAD

**Issue by eusebiu** [BeardedManStudios/ForgeNetworkingRemastered#305]
### Version Number and Operating System(s):
Latest from AssetStore or master (Unity folder)

### Expected behavior:
I am creating a scenario with one player entering **late** to the session. So, I would expect that the Instantiated objects to be recreated and sometimes they are. But sometimes they are not and I see this exception in the console.

### Actual behavior:
Get exception:
MissingReferenceException: The object of type 'MySyncObject' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
BeardedManStudios.Forge.Networking.Generated.MySyncObjectBehavior+<>c__DisplayClass2_0.<Initialize>b__1 () (at Assets/Bearded Man Studios Inc/Generated/UserGenerated/MySyncObjectBehavior.cs:52)
BeardedManStudios.Forge.Networking.Unity.MainThreadManager.HandleActions (BeardedManStudios.Forge.Networking.Unity.MainThreadManager+UpdateType updateType) (at Assets/Bearded Man Studios Inc/Scripts/MainThreadManager.cs:165)
BeardedManStudios.Forge.Networking.Unity.MainThreadManager.FixedUpdate () (at Assets/Bearded Man Studios Inc/Scripts/MainThreadManager.cs:171)

### Steps to reproduce:
Setup host = server.Connect();
Instantiate some network objects and move them around = NetworkManager.Instance.InstantiateMySyncObject()
Join session = client.Connect(ServerAddress, ServerPort);
=> Exceptions appear in the console

**Comment by phalasz** [comment]
Could you provide an example project that reproduces this error please?

**Comment by eusebiu** [comment]
Not at the moment as I am really busy with my project. :(
Any first ideas why this might happen?

**Comment by NFMynster** [comment]
Make sure you unsubscribe from any possible event you might be using.

**Comment by eusebiu** [comment]
I think I found one possible reason - I noticed that the `var go = Instantiate(MySyncObjectNetworkObject[obj.CreateCode]);` is called before OnSceneUnloaded => So, the network object is created in a dying scene.

Some context: I am trying to reuse the scene when setting up the multi-player environment (i.e. there is no scene where the IP address and port are entered and with Host/Join button).
The host does: 
`server = new UDPServer(64);
((UDPServer)server).Connect(ServerAddress, ServerPort);
...
networkManager = GameObject.Instantiate(NetworkManager).GetComponent<NetworkManager>();
networkManager.Initialize(networker, "", 0, null);
networkManager.SceneReady(UnityEngine.SceneManagement.SceneManager.GetActiveScene(), UnityEngine.SceneManagement.LoadSceneMode.Single); // has no effect for host`

The client does:
`client = new UDPClient();
((UDPClient)client).Connect(ServerAddress, ServerPort);
...
networkManager = GameObject.Instantiate(NetworkManager).GetComponent<NetworkManager>();
networkManager.Initialize(networker, "", 0, null);
networkManager.SceneReady(UnityEngine.SceneManagement.SceneManager.GetActiveScene(), UnityEngine.SceneManagement.LoadSceneMode.Single);`

How can I make sure that the Instantiate(..) call is made after the Scene was reloaded?

**Comment by phalasz** [comment]
Which instantiate call? This?
`networkManager = GameObject.Instantiate(NetworkManager).GetComponent<NetworkManager>();` ?

**Comment by eusebiu** [comment]
I am referring to this code:
var go = Instantiate(MySyncObjectNetworkObject[obj.CreateCode]);

Unfortunately, I cannot share the code... :(

**Comment by NFMynster** [comment]
You closed the issue, did it fix it using the network manager's instantiate?

**Comment by phalasz** [comment]
Can you give use a simple barebones example that reproduces this issue? We are not looking to see your whole project just a simple example that showcases the issue so we can fix it or advise on how to not run into it.

**Comment by eusebiu** [comment]
Sorry, I did not want to close it.
I "fixed" it by waiting for the Camera to be instantiated (?). In my Player network object NetworkStart, I start listening for some commands to be synced which are related to the MySyncObjectNetworkObject (e.g. a load command creates an instance of MySyncObject which is synced using Forge).
Using that if (Camera.main) condition somehow ensures that the scene and objects are in sync...

`
protected override void NetworkStart()
{
    base.NetworkStart();

    if (networkObject.IsOwner)
        StartCoroutine(ProcessClientCommands()); 
}

IEnumerator ProcessClientCommands()
{
    ...
    if (Camera.main == null)
        yield return null;
    ...
}
`

**Comment by NFMynster** [comment]
Do you reference the camera anywhere in network start? Are you using IL2CPP?

**Comment by eusebiu** [comment]
No. If I remember correctly there was a random occurring error which was due to missing Camera but in a completely different location (I guess also because scene reloading).
Not using IL2CPP.

**Comment by phalasz** [comment]
If you are happy that it is solved then feel free to close this issue.

**Comment by eusebiu** [comment]
Thanks for your quick answers, nevertheless! :)
