### ISSUE TITLE
InvalidCastException

### ISSUE THREAD

**Issue by LijpeLynn** [BeardedManStudios/ForgeNetworkingRemastered#317]
### Version Number and Operating System(s):
Forge Networking Remastered Version 03/10/2018-19.53.38,04
Unity 2018.3.8f1 Personal

### Expected behavior:
The client joins without an InvalidCastException.

### Actual behavior:
The client joins with an InvalidCastException, this error refers to the SyncPlayerNetworkObject.
As a result the clients game experience is not what it should be.

### Steps to reproduce:
Download Link: [Download](https://drive.google.com/file/d/1eTsTvbFTGuDc1rIlNxMsH_X0EQhwqD1k/view?usp=sharing)
Build and run the project, host the game with the builded one and connect with Unity in play mode. Click the start game button on the host.

#### [Optional] Discord Username:
Lijpe Lynn#4689

**Comment by phalasz** [comment]
@LijpeLynn is this issue happening because not all network object arrays in the networkmanager have a prefab assigned?

**Comment by Yooooomi** [comment]
Still happening with me, exact same behaviour

**Comment by phalasz** [comment]
could you share a project that reproduces the issue please?

**Comment by Yooooomi** [comment]
Here: https://drive.google.com/open?id=1CEej6B8XxVIcV5p-uGfRL6cGutFgFAcs

**Comment by LijpeLynn** [comment]
I solved the problem

**Comment by FpardoLearning** [comment]
@LijpeLynn How you solved it?

**Comment by LijpeLynn** [comment]
@FpardoLearning I fixed it by not having multiple NetworkBehaviors on one GameObject.
