### ISSUE TITLE
what about some tutorial for 0 to working game?

### ISSUE THREAD

**Issue by RYG81** [BeardedManStudios/ForgeNetworkingRemastered#33]
It would be great if you guys invest little time on making some 0-to working game tutorials. It will help understand full process.

**Comment by baflink** [comment]
Thanks for the feedback. We've gotten requests similar to this so we'll be working on some more "from 0" kinds of tutorials to get people started outside of using the provided options.

**Comment by RYG81** [comment]
Thanks

**Comment by BrianWiz** [comment]
@RYG81 

Head on over to their website, they've got some tutorials there for creating a chat system, and they're in the works with more. They're under a cheap paywall ($5), unless you are already a supporter, contact them on Discord.
https://beardedmanstudios.com/learn/unity/multiplayer/unity-online-multiplayer-chat-system/
