### ISSUE TITLE
Register not working

### ISSUE THREAD

**Issue by dummyghost** [BeardedManStudios/ForgeNetworkingRemastered#333]
Hello BeardedManStudio,

I am not able to Register on your website.
I have filled all of the details and i have got an email containing a link and when i open the link it says server ip address could not be found  ERR_NAME_NOT_RESOLVED.
Link: https://beardedmanstudios.com/join-us/registration/

And when i register using https://developers.forgepowered.com/Register this site it shows blank white screen.

I want to use Forge remastered in one of game.I don't know where to contact you guys so i am posting it here. Please help me.

Thanks

**Comment by NFMynster** [comment]
Hello, firstly, the site is not used any more, everything is open source. You can get direct support from the Discord, which is linked on this repository's readme :)

**Comment by dummyghost** [comment]
ok Thanks
