### ISSUE TITLE
Version number of forge remastered.

### ISSUE THREAD

**Issue by JesusLuvsYooh** [BeardedManStudios/ForgeNetworkingRemastered#335]
Hi, i have got and tried the Unity Forge remastered from a few areas online, Unity store, this Git, and the 'nightly builds' unity package.
The version numbers for it in - Window / Forge Networking / About, all say different, this Git, even though parts have been updated recently, says 2018 in the about section.

My question is, how do i know which is 'true' latest version?
Thank you.

**Comment by phalasz** [comment]
Sorted on discord.
