### ISSUE TITLE
Is it possible to set up a Database like MySQL with Forge?

### ISSUE THREAD

**Issue by F4bsl** [BeardedManStudios/ForgeNetworkingRemastered#343]
Sorry this is probably the wrong section but i don't know where to ask for this ^^. Do you know if its possible to connect the Forge Server with a database? And if so can you maybe give some quick tips to make it secure? Or should i just connect unity directly with the database? I've found some good tutorials on that topic. But how will the connection with the server work? I know this is a noob question but im very interested in this. thanks in advance for any kind of advice :)

**Comment by tommohawkaction** [comment]
Hi F4bsl, yeah this is the wrong place, in future jump on our discord and ask in the #beginners-questions/#networking-questions.

Think of Forge as a communication system, so yes you can set up a database like mysql with Forge as it has no relation with Forge. All you need to do is setup the MySQL database and then use it as you would normally.

That being said, security. So all depends on how you want your users to access the data. I wouldn't be surprised if there is a way to make your MySQL data only readable to people who don't have the password. The most secure way to handle a database is probably to do some dedicated server which you the developer host and has access to the database, and then communicate the data to the client, this way you are the only person who has access to the database and your dedicated server is the middle man between the two.

Hope this helps, in future ask in the Discord
https://discord.gg/NgrUHA

**Comment by F4bsl** [comment]
Ok thanks a lot :) this really helps me and is also ensuring im going in the right direction. And sorry again for the being in wrong section.
