### ISSUE TITLE
Null reference exception in lobby scene

### ISSUE THREAD

**Issue by TheLogan** [BeardedManStudios/ForgeNetworkingRemastered#345]
### Version Number and Operating System(s):
v26, windows 10

### Expected behavior:
null reference exception should not be cast

### Actual behavior:
null reference is cast

### Steps to reproduce:
open the lobby scene and click play

### additional
Essentially what's happening is that the LobbyManager.cs is relying on there being a NetworkManager.cs in the scene, there isn't one. And the get function of the NetworkManager isn't written in a way where it can just instantiate a new one in case it's missing.
Also, just pulling in the NetworkManager prefab will fail as NetworkManager tries to run Networker.IsServer, but Networker hasn't been set either.

**Comment by phalasz** [comment]
You still need to start from the multiplayer menu to set everything up.

**Comment by TheLogan** [comment]
Doh, yeah I see that now. Thanks for the response :)
