### ISSUE TITLE
ForgeNetworkingCommon.dll not found to build StandAloneServer

### ISSUE THREAD

**Issue by ehsanwwe** [BeardedManStudios/ForgeNetworkingRemastered#375]
hi
i open the repo upgrade it to .net4.5
everything is ok 
but in the main CSPROJ (BeardedManStudios.csproj) i cant see any CS file every cs is missing so i cant build the ForgeNetworkingCommon.dll 

------------------
if owner of this repo want to hide it please send me the dll file for starting my Server 
thnx

**Comment by phalasz** [comment]
As mentioned on discord please see https://github.com/BeardedManStudios/ForgeNetworkingRemastered/wiki/Modify-Master-and-Standalone-servers
