### ISSUE TITLE
[NCW] Deleted classes still compile behavior when hitting "Save & Compile"

### ISSUE THREAD

**Issue by mcguinnessdr** [BeardedManStudios/ForgeNetworkingRemastered#38]
### Version Number and Operating System(s)
Latest Develop branch, commit cad82c4
Unity 2017.1.0f3
Windows 10

### Expected behavior
Deleted classes should not compile a new "behavior" script.

### Actual behavior
Deleted class's "behavior" script gets compiled.

### Steps to reproduce
Open NCW.
Delete a class.
Open another class.
Hit "Save & Compile".
A "behavior" script is created for the previously deleted class.

**Comment by baflink** [comment]
More info if needed from duplicate ticket: #48

**Comment by phalasz** [comment]
Is this still an issue? Can this be closed?
