### ISSUE TITLE
Master server is not working

### ISSUE THREAD

**Issue by lb4business** [BeardedManStudios/ForgeNetworkingRemastered#40]
### Version Number and Operating System(s):
Hosting: Win Server 2012. Clients - Editor (unity 5.6) /Win build (win7) /android build

### Expected behavior:
Connects as in local network

### Actual behavior:
Method Connected(NetWorker networker) is firing, but i cant see networked objects and send/recieve any data

### Steps to reproduce:
1) Create empty project
2) integrate FNR, set Master Server in Server browser and Multiplayer Menu
3) Create win buil 
4) Host server on build
5) Run Server Browser scene on Editor
6) Connect by button in server list

#### [Optional] Discord Username:
Leonid B

**Comment by baflink** [comment]
Are you using the master server from the develop branch for this?

**Comment by lb4business** [comment]
Yep, FNR, Master and NAT - all from develop branch

**Comment by baflink** [comment]
I successfully connected on the latest master branch

**Comment by lb4business** [comment]
i've tested today using latest master branch server. 
Server on android device, client on Editor: client connected, but server owned gameobject dont spawned
Server on Editor, client on Android device: no connection.
