### ISSUE TITLE
Wiki Documentation feedback

### ISSUE THREAD

**Issue by JamesMcGhee** [BeardedManStudios/ForgeNetworkingRemastered#408]
The article located here
https://github.com/BeardedManStudios/ForgeNetworkingRemastered/wiki/Overview

Provides instructions for installing Steamworks.NET via the releases section. This would have the user install Steamworks.NET via the exported unity package which does not include the latest changes and does not include the Steamworks.NET assembly definitions.

You could simplify that article and the end user's effort in stalling Steamworks.NET by telling them the following

1. Open Unity 2019 LTS (latest build) or a more recent version of Unity preferably an LTS release
2. Open the Unity Package Manager
3. Click the "+" (plus) button located in the upper left of the window; 
4. Select the "Add package from git URL..." option
5. Enter the following URL: `https://github.com/rlabrecque/Steamworks.NET.git?path=/com.rlabrecque.steamworks.net`
6. Click the "Add" button and wait several seconds for the system to download and install the Steamworks.NET package from GitHub.

This would cause the latest version of Steamworks.NET to be imported and it would include the asembly definition file which is required by other assets that use Steamworks.NET

As a side note we are an asset developer our selves and publish a Steamworks integration with Unity including both free and paid versions. They include full documentation, support, video tutorials and more. you can learn more at our KB here.

https://kb.heathenengineering.com/assets/steamworks

### Version Number and Operating System(s):
NA

### Expected behavior:
NA

### Actual behavior:
NA

### Steps to reproduce:
NA

#### [Optional] Discord Username:
Loden | Heathen Engineering#6213

**Comment by TheYellowArchitect** [comment]
Hello!

I wrote the Steamworks integration part of the wiki, and I have to admit it was a rushed job. The final part is especially indicative.
But when I returned to "polish" it, I noticed that the videos do a far better job than whatever I had planned to write, so I kept them as they are. Whatever I would write would be a text transcription of the video, so it just wasn't worth it.

Anyway, wiki is editable by anyone. If you can confirm your guide worked step-by-step, feel free to write it :+1:
