### ISSUE TITLE
Nat Hole Punch server is crashing

### ISSUE THREAD

**Issue by lb4business** [BeardedManStudios/ForgeNetworkingRemastered#41]
### Version Number and Operating System(s):
Nat Hole Punch server fro develop branch, Windows Server 2012

### Expected behavior:
Works without crashes

### Actual behavior:
Crushes after 2 connects

### Steps to reproduce:
run NAT, connect couple of times

**Comment by phalasz** [comment]
Is this still an issue? Can this be closed?
