### ISSUE TITLE
Master Server and NAT consumes a lot of processing time

### ISSUE THREAD

**Issue by lb4business** [BeardedManStudios/ForgeNetworkingRemastered#42]
### Version Number and Operating System(s):
Master Server and NAT from develop branch, Hosting: Windows Server 2012 / Ubuntu / Windows 7

### Expected behavior:
Dont consume so much processing power

### Actual behavior:
100% core load

### Steps to reproduce:
Run.

**Comment by baflink** [comment]
Seems like a threading issue, need to make sure to relieve the CPU on the various threads.

**Comment by baflink** [comment]
Fixes on develop
