### ISSUE TITLE
Deleted NetworkObject in NCW keeps coming back.

### ISSUE THREAD

**Issue by Espii** [BeardedManStudios/ForgeNetworkingRemastered#48]
1. Create TestNetworkObject in the NCW.
2. Press trashcan next to TestNetworkObject to delete
3. Open any existing networkobject and hit "Save & Compile", or create a new networkobject.
The script for TestNetworkObject will be generated even though it has been deleted and will continue to do so every time I make a change to NCW

Found a temporary fix from Brent on discord where if i delete the file, FNWizardData.bin, the problem gets resolved.

**Comment by baflink** [comment]
Found out that this was a duplicate of #38
