### ISSUE TITLE
Lan Discovery still not working - build provided

### ISSUE THREAD

**Issue by theWill** [BeardedManStudios/ForgeNetworkingRemastered#52]
### Version Number and Operating System(s):
latest develop as of Aug 7 2017

### Expected behavior:
as client connect, disconnect, then issue lan discovery works again to connect.

### Actual behavior:
as client can connect, disconnect, but then cannot reconnect again using lan discovery

### Steps to reproduce:
download build here: 
https://app.box.com/s/0nk43a9xl2jiol9d2cp2dibz3qu2bn1q

unzip 
new project in unity
import package 

add scenes to build:
titlev3
main
funnel
mixup
plots

build and run
for host:
1) select multiplayer
2) select host
3) choose any map
scene changes and wait for client to join ...

on client (either run another build or the unity player)
1) select multiplayer
2) select join (fires lan disco) and should auto-join the host

... now back on the host hit start game
... now on the client click the upper left hand "pause" icon
return to title screen. (this disconnects from host)

... now back on the host do the same as the client return to title.
then host another game.

... now back on the client click multiplayer
... Join - cannot find host (Lan discovery fails!)

**Comment by theWill** [comment]
Files of Note: 
ConnectionManager.cs has the landiscovery event code
GameManager has my copy of the MultiplayerMenu client/host code
MatchMenuManager has the disconnect code in returnToTitle()

**Comment by baflink** [comment]
I'm going to close this. If you still have issues, please let me know @theWill. We can re-open this ticket
