### ISSUE TITLE
Delay finalize call in RemovePlayer method

### ISSUE THREAD

**Issue by BrentFarris** [BeardedManStudios/ForgeNetworkingRemastered#55]
### Version Number and Operating System(s):
Latest Master branch

### Expected behavior:
There use to be a sleep for 500ms when testing, instead of doing that the `FinalizeRemovePlayer` method should be moved to a thread and delayed on that thread since it is called on the server

### Actual behavior:
Potential that the client doesn't get the disconnect message

### Steps to reproduce:
Disconnect a client forcefully

**Comment by SmiggsGDog** [comment]
Fix appears to have broken cube forge example. 
Repo - start server, connect client, disconnect client. Player count will continue to reduce perpetually.
