### ISSUE TITLE
Fields skipping dirty check

### ISSUE THREAD

**Issue by BrianWiz** [BeardedManStudios/ForgeNetworkingRemastered#73]
### Version Number and Operating System(s):
v24 and Windows 10

EDIT:
v24.1, Windows 10, Unity 2017.1.0f3

### Expected behavior:
Fields send only when they're dirty

### Actual behavior:
Fields are sending every update interval even if never changed

### Steps to reproduce:
Tested by running a field change event
```   
   protected override void NetworkStart()
   {
      base.NetworkStart();
      networkObject.positionChanged += PositionChanged;
   }
   private void PositionChanged(Vector2 position, ulong test)
   {
        MainThreadManager.Run(() =>
        {
            Debug.Log("test");
        });
   }
```

#### [Optional] Discord Username:
NoMercy

**Comment by BrianWiz** [comment]
@baflink 
I've tested with the latest commit and something still isn't right. It seems like field change events now fire if an RPC is sent from the client. Though I can't quite tell for sure, but I'm pretty sure that's what's happening. Or maybe it's receiving _any_ field updates from the server causing them to fire?

For example I have a uint, I set it once on the server and only once, yet when I move, it's change event seems to fire.

I'll keep investigating.

**Comment by baflink** [comment]
@BrianWiz Can you try with the newest NetworkObjectTemplate.txt on develop?

**Comment by BrianWiz** [comment]
@baflink Finally got around to testing this. There is still a problem.

I've got two fields, one is "`position`" (Vector2), one is "`test`" (int). I set `test` once in NetworkStart(), and I set `position` in Update();

The result is that the testChanged event fires every time position is changed. So it looks like if any field is changed, it thinks they all changed.

Here's my code

```protected override void NetworkStart()
    {
        base.NetworkStart();

        // 20ms update interval
        networkObject.UpdateInterval = 20;

        if (networkObject.IsServer)
        {
            networkObject.test = 2;
        }
        else
        {
            networkObject.testChanged += TestChanged;
        }
    }```

```
    void Update()
    {
        if (networkObject != null)
        {
            if (networkObject.IsServer)
            {
                networkObject.position = transform.position;
            }
        }
    }
```

```
private void TestChanged(int test, ulong timestamp)
{
    Debug.Log("test");
}
```

**Comment by BrianWiz** [comment]
@baflink So it looks like on the server, in `SerializeDirtyFields()`, it looks like it returns `dirtyFieldsData` with fields that shouldn't actually be dirty.

So it looks like if any field is dirty, it sends them all of them over in `HeartBeat()` on `NetworkObject.cs`. If none are dirty, it doesn't send anything as expected.
