### ISSUE TITLE
i send a text but can not get the same text why?

### ISSUE THREAD

**Issue by cnbryan** [BeardedManStudios/ForgeNetworkingRemastered#74]
Text temp = Text.CreateFromString(networkHandle.Time.Timestep, "abcdefg", true, Receivers.All,55, true);
networkHandle.send(temp);
how can i get abcdefg only ?
------------
 private static void NetworkHandle_textMessageReceived(NetworkingPlayer player, Text frame, NetWorker sender)
｛
frame.tostring()?---------------here can not get "abcdefg" only ,, i just get "abcdefg口"
｝
-----------

**Comment by baflink** [comment]
I will test this in the example cube forge scene to see what is going on. I am assuming that you are on TCP?

**Comment by baflink** [comment]
I know what the issue is for this and it will be resolved tonight
