### ISSUE TITLE
Forge not correctly registering RPCs

### ISSUE THREAD

**Issue by SmiggsGDog** [BeardedManStudios/ForgeNetworkingRemastered#80]
### Version Number and Operating System(s):
Git pulled on the 30/8/17 - Win 10

### Expected behavior:
When each client connects they should have network instantiated prefabs created for them and RPCs should be registered.

### Actual behavior:
From time to time Forge fails to spawn some instantiated prefabs and some RPCs wont work on others. It appears that the some RPCs are not registered.

### Steps to reproduce:
Start a cubeforge server. Make a couple of changes to the world and then connect in about 10 clients. You will notice some of the players don't get the world state.

#### [Optional] Discord Username:
SmiggsGDog

**Comment by SmiggsGDog** [comment]
Updated to detail that this issue is not only related to cubeforge.

**Comment by phalasz** [comment]
Is this still an issue? Can this be closed now?

**Comment by PyeonggukLee** [comment]
@phalasz I think this didn't get fixed yet.
I've had a same/similar problem as this issue, so made a fix for this:
https://github.com/BeardedManStudios/ForgeNetworkingRemastered/pull/270

the related issue as I guess: #107

**Comment by Balroth** [comment]
Pretty sure this can be safely closed, since @PyeonggukLee 's fix #270 , was merged into the master branch

**Comment by PyeonggukLee** [comment]
I think #107 is the identical one with this issue.
