### ISSUE TITLE
LobbySystem.prefab is corrupted

### ISSUE THREAD

**Issue by kamyker** [BeardedManStudios/ForgeNetworkingRemastered#81]
### Version Number and Operating System(s):
Aug 16, 2017, Win 10

### Expected behavior:
Usable prefab

### Actual behavior:
Prefab somehow stopped working after last commit 
![a41561f117c3c3b87ef5d4e3555ec931](https://user-images.githubusercontent.com/9093037/30005754-b92eb658-90e9-11e7-8171-a8fe4a208949.png)

Tried unity 5.4.4, 5.6.3 and 2017.1

Prefab from Aug 9, 2017 works correctly.

### Steps to reproduce:
Drag and drop prefab file to unity or import last package

#### [Optional] Discord Username:
Kamyker

**Comment by KirkStallings** [comment]
A pull request has been submitted to fix this bug.
