### ISSUE TITLE
Unable to send Unity types in current dev build

### ISSUE THREAD

**Issue by SmiggsGDog** [BeardedManStudios/ForgeNetworkingRemastered#98]
### Version Number and Operating System(s):
Git Dev Pull from 24/9/2017 - Win 10 Unity 2017.1.p3

### Expected behavior:
Should be able to send Unity types Vector3 and Quaternions

### Actual behavior:
BaseNetworkException: The type UnityEngine.Vector3 is not allowed to be sent over the Network (yet)
BeardedManStudios.Forge.Networking.ObjectMapper.GetBytesArray (System.Object o, System.Type type) (at Assets/Bearded Man Studios Inc/Source/Forge/Networking/ObjectMapper.cs:474)
BeardedManStudios.Forge.Networking.ObjectMapper.MapBytes (BeardedManStudios.BMSByte bytes, System.Object[] args) (at Assets/Bearded Man Studios Inc/Source/Forge/Networking/ObjectMapper.cs:236)
BeardedManStudios.Forge.Networking.Unity.NetworkManager.InstantiateNetworkCamera (Int32 index, Nullable`1 position, Nullable`1 rotation, Boolean sendTransform) (at Assets/Bearded Man Studios Inc/Generated/NetworkManager.cs:364)
CubeForgeGame.Start () (at Assets/Bearded Man Studios Inc/Examples/Cube Forge/Scripts/CubeForgeGame.cs:74)

Appears that the UnityObjectMapper doesn't work anymore.

### Steps to reproduce:
Instantiate doesn't work so a simple run of cubeforge or the like will reproduce.

#### [Optional] Discord Username
SmiggsGDogg

**Comment by SmiggsGDog** [comment]
Bug is related to new static class created for mapping bytes. The old system used a singleton instance which changed between UnityObjectMapper and ObjectMapper based on if forge was running in Unity or Standalone. The recent changes made by @kamyker don't appear to account for this.

**Comment by kamyker** [comment]
Try this: https://github.com/BeardedManStudios/ForgeNetworkingRemastered/pull/99
